# Generated by Django 4.0.4 on 2022-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaccineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('HumanId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('zipCode', models.PositiveIntegerField(null=True)),
                ('landLine', models.CharField(max_length=100)),
                ('cellularPhone', models.CharField(max_length=20)),
                ('infected', models.BooleanField()),
                ('conditions', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Humen',
        ),
    ]
